---
- name: install remi repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

- name: install php
  yum: pkg=php state=present enablerepo=remi

- name: install php-fpm
  yum: pkg=php-fpm state=present enablerepo=remi
  
- name: install php-mysqlnd
  yum: pkg=php-mysqlnd state=present enablerepo=remi
  
- name: install php-mbstring
  yum: pkg=php-mbstring state=present enablerepo=remi
  
- name: install php-bcmath
  yum: pkg=php-bcmath state=present enablerepo=remi
  
- name: install php-gd
  yum: pkg=php-gd state=present enablerepo=remi
  
- name: install php-xml
  yum: pkg=php-xml state=present enablerepo=remi
  
- name: install php-mcrypt
  yum: pkg=php-mcrypt state=present enablerepo=remi
  
- name: install php-pear
  yum: pkg=php-pear state=present enablerepo=remi
  
- name: install php-devel
  yum: pkg=php-devel state=present enablerepo=remi
  
- name: install pcre-devel
  yum: pkg=pcre-devel state=present enablerepo=remi

- name: copy www.conf
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf
  tags: conf

- name: mkdir /var/log/php-fpm
  file: path=/var/log/php-fpm owner=nginx group=wheel state=directory mode=775

- name: mkdir /var/run/php-fpm
  file: path=/var/run/php-fpm owner=nginx group=wheel state=directory mode=777
  
- name: mkdir /var/lib/php/session
  file: path=/var/nginx owner=nginx group=wheel state=directory mode=775

- name: edit typezone
  lineinfile: 
    regexp='^date.timezone'
    line='date.timezone = Asia/Tokyo'
    insertafter=EOF
    state=present
    dest=/etc/php.ini

- name: edit post_max_size
  lineinfile: 
    regexp='^post_max_size'
    line='post_max_size = 32M'
    insertafter=EOF
    state=present
    dest=/etc/php.ini
    
- name: edit max_input_time
  lineinfile: 
    regexp='^max_input_time'
    line='max_input_time = 300'
    insertafter=EOF
    state=present
    dest=/etc/php.ini

- name: edit max_execution_time
  lineinfile: 
    regexp='^max_execution_time'
    line='max_execution_time = 300'
    insertafter=EOF
    state=present
    dest=/etc/php.ini
    
- name: start php-fpm service
  service: name=php-fpm state=started enabled=yes

  
  