- hosts: all
  user: pky
  sudo: true
  roles:
    - iptables    
    - common

- hosts: server
  user: pky
  sudo: true
  roles:
    - mysql
    - nginx
    - spawn-fcgi
    - owncloud
    - reboot
    
