---

- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm state=present

- name: install zabbix agent
  yum: pkg=zabbix-agent state=present

- name: zabbix agent config file
  template: >
    src=zabbix_agentd.conf.j2
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=zabbix
    group=zabbix
    mode=0644

- name: mkdir /etc/zabbix/zabbix_agentd.d/
  file: path=/etc/zabbix/zabbix_agentd.d/ owner=zabbix group=zabbix state=directory mode=775

- name: start zabbix agent service
  service: name=zabbix-agent state=restarted enabled=yes
